# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2946cba98d1ef37c46dc744fa4a991fe557baef47523e4ae5bff39873aaa930183ff0b42bb4b71b81232bb6b27a53962825d84e340d640374eff6de5ef880617

test:
  secret_key_base: 88f6bc623d0f4dddb604a5d4417980b14fb2c7ef966bd3bdeb4a58a7dd357e8b85800ff43b764bf48c5d6cb2aab6b05e0af1afd3dcb26997955283da81716b0e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
